version: "3"

services:
  web:
    container_name: "web"
    build:
      context: "./web"
      dockerfile: Dockerfile
    expose:
      - 8080
    command: "uwsgi --ini /app/uwsgi.ini"
  nginx:
    container_name: "nginx"
    build:
      context: "./nginx"
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - "web"